package com.dyz.myBatis.model;

public class Account {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.Uuid
     *
     * @mbggenerated
     */
    private Integer uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.openid
     *
     * @mbggenerated
     */
    private String openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.nickName
     *
     * @mbggenerated
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.headIcon
     *
     * @mbggenerated
     */
    private String headicon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.roomCard
     *
     * @mbggenerated
     */
    private Integer roomcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.unionid
     *
     * @mbggenerated
     */
    private String unionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.province
     *
     * @mbggenerated
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.city
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.sex
     *
     * @mbggenerated
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.prizeCount
     *
     * @mbggenerated
     */
    private Integer prizecount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.id
     *
     * @return the value of account.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.id
     *
     * @param id the value for account.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.Uuid
     *
     * @return the value of account.Uuid
     *
     * @mbggenerated
     */
    public Integer getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.Uuid
     *
     * @param uuid the value for account.Uuid
     *
     * @mbggenerated
     */
    public void setUuid(Integer uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.openid
     *
     * @return the value of account.openid
     *
     * @mbggenerated
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.openid
     *
     * @param openid the value for account.openid
     *
     * @mbggenerated
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.nickName
     *
     * @return the value of account.nickName
     *
     * @mbggenerated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.nickName
     *
     * @param nickname the value for account.nickName
     *
     * @mbggenerated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.headIcon
     *
     * @return the value of account.headIcon
     *
     * @mbggenerated
     */
    public String getHeadicon() {
        return headicon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.headIcon
     *
     * @param headicon the value for account.headIcon
     *
     * @mbggenerated
     */
    public void setHeadicon(String headicon) {
        this.headicon = headicon == null ? null : headicon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.roomCard
     *
     * @return the value of account.roomCard
     *
     * @mbggenerated
     */
    public Integer getRoomcard() {
        return roomcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.roomCard
     *
     * @param roomcard the value for account.roomCard
     *
     * @mbggenerated
     */
    public void setRoomcard(Integer roomcard) {
        this.roomcard = roomcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.unionid
     *
     * @return the value of account.unionid
     *
     * @mbggenerated
     */
    public String getUnionid() {
        return unionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.unionid
     *
     * @param unionid the value for account.unionid
     *
     * @mbggenerated
     */
    public void setUnionid(String unionid) {
        this.unionid = unionid == null ? null : unionid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.province
     *
     * @return the value of account.province
     *
     * @mbggenerated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.province
     *
     * @param province the value for account.province
     *
     * @mbggenerated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.city
     *
     * @return the value of account.city
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.city
     *
     * @param city the value for account.city
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.sex
     *
     * @return the value of account.sex
     *
     * @mbggenerated
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.sex
     *
     * @param sex the value for account.sex
     *
     * @mbggenerated
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.prizeCount
     *
     * @return the value of account.prizeCount
     *
     * @mbggenerated
     */
    public Integer getPrizecount() {
        return prizecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.prizeCount
     *
     * @param prizecount the value for account.prizeCount
     *
     * @mbggenerated
     */
    public void setPrizecount(Integer prizecount) {
        this.prizecount = prizecount;
    }
}